
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun May 30 22:01:02 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 13;
  public static final int IDENT = 15;
  public static final int NUMBER = 4;
  public static final int PROG = 12;
  public static final int VOID = 11;
  public static final int SEMI = 8;
  public static final int EQUAL = 6;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int RPAREN = 10;
  public static final int PRINT = 2;
  public static final int RETURN = 3;
  public static final int RBRACE = 14;
  public static final int LPAREN = 9;
}

