
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 27 13:46:58 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 10;
  public static final int YIELD = 51;
  public static final int CASE = 18;
  public static final int LPAREN = 42;
  public static final int SEMI = 39;
  public static final int GREATER = 30;
  public static final int CONTINUE = 9;
  public static final int LESS = 32;
  public static final int RPAREN = 43;
  public static final int NOTEQUALLY = 29;
  public static final int AND = 34;
  public static final int OR = 35;
  public static final int COMMA = 40;
  public static final int DDOT = 49;
  public static final int CLASS = 12;
  public static final int INC = 37;
  public static final int DIV = 26;
  public static final int LESSEQ = 33;
  public static final int IF = 16;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int EQUAL = 36;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int ADD = 23;
  public static final int NUMBER = 2;
  public static final int MOD = 27;
  public static final int BREAK = 7;
  public static final int IDENT = 5;
  public static final int VOID = 11;
  public static final int SWITCH = 17;
  public static final int LBRACE = 44;
  public static final int ELSE = 15;
  public static final int LSQUARE = 46;
  public static final int READ = 22;
  public static final int GOTO = 52;
  public static final int RSQUARE = 47;
  public static final int CHARCONST = 3;
  public static final int WHILE = 20;
  public static final int DEFAULT = 50;
  public static final int RBRACE = 45;
  public static final int BOOLCONST = 4;
  public static final int EXTENDS = 13;
  public static final int PROG = 6;
  public static final int EQUALLY = 28;
  public static final int QUESTION = 48;
  public static final int GREATEREQ = 31;
  public static final int DEC = 38;
  public static final int SUB = 24;
  public static final int PRINT = 21;
  public static final int DO = 19;
}

